WebResurection/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebResurection.Domain.Model;
using WebResurection.Repositories.EF;
using PagedList;
using System.Data.Entity.Infrastructure;
using WebResurection.Domain.Model.Characters;

namespace WebResurection.Controllers
{
    public class PlayerController : Controller
    {
        private WebResurection_Context db = new WebResurection_Context();

        // GET: Player
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var players = from p in db.Characters
                          .Include(x => x.ImplementedStats)
                          .Include(x => x.ImplementedStats)
                          where p.isPlayer == true
                          select p;

            //If searchstring changes then go to the first page 
            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;
            ViewBag.CurrentFilter = searchString;


            if (!String.IsNullOrEmpty(searchString))
                players = players.Where(p => p.FirstName.Contains(searchString));

            switch (sortOrder)
            {
                case "name_desc":
                    players = players.OrderByDescending(p => p.FirstName);
                    break;
                case "Date":
                    players = players.OrderBy(p => p.CreateDate);
                    break;
                case "date_desc":
                    players = players.OrderByDescending(p => p.CreateDate);
                    break;
                default:
                    players = players.OrderBy(p => p.FirstName);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(players.ToPagedList(pageNumber, pageSize));
        }

        // GET: Player/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Player player = db.Players.Find(id);

            //if (player == null)
            //{
            //    return HttpNotFound();
            //}
            Character character = db.Characters.Find(id);


            if (!character.isPlayer)
            {
                return HttpNotFound();
            }

            return View(character);
        }

        // GET: Player/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Player/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FirstName,LastName,Character")] Player player, string command)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string difficulty = Request.Params["difficulty"];

                    player.Create(difficulty);
                    player.Character.CreatePlayerStats(db.Stats.ToList(), player.Difficulty);

                    db.Players.Add(player);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException)
            {
                //Log the error
                //ModelState.AddModelError("", "Unable to save changes. Try agian, and if the problem persists call I.T");
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(player);
        }

        ////// GET: Player/Edit/5
        ////public ActionResult Edit(int? id)
        ////{
        ////    if (id == null)
        ////    {
        ////        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        ////    }
        ////    Player player = db.Players.Find(id);
        ////    if (player == null)
        ////    {
        ////        return HttpNotFound();
        ////    }
        ////    return View(player);
        ////}

        //// POST: Player/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        ////[HttpPost]
        ////[ValidateAntiForgeryToken]
        ////public ActionResult Edit([Bind(Include = "ID,Name,HealthPoints,Damage")] Player player)
        ////{
        ////    if (ModelState.IsValid)
        ////    {
        ////        db.Entry(player).State = EntityState.Modified;
        ////        db.SaveChanges();
        ////        return RedirectToAction("Index");
        ////    }
        ////    return View(player);
        ////}
        ////[HttpPost, ActionName("Edit")]
        ////[ValidateAntiForgeryToken]
        ////public ActionResult EditPost(int? id)
        ////{
        ////    if (id == null)
        ////    {
        ////        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        ////    }
        ////    var studentToUpdate = db.Players.Find(id);
        ////    if (TryUpdateModel(studentToUpdate, "",
        ////       new string[] { "Name", "HealthPoints", "Damage" }))
        ////    {
        ////        try
        ////        {
        ////            db.SaveChanges();

        ////            return RedirectToAction("Index");
        ////        }
        ////        catch (RetryLimitExceededException /* dex */)
        ////        {
        ////            //Log the error (uncomment dex variable name and add a line here to write a log.
        ////            //ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
        ////            ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
        ////        }
        ////    }
        ////    return View(studentToUpdate);
        ////}

        // GET: Player/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persist call I.T";
            }
            Character character = db.Characters.Find(id);
            //Player player = db.Players.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // POST: Player/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Character character = db.Characters.Find(id);
                //Player player = db.Players.Find(id);
                db.Characters.Remove(character);
                db.SaveChanges();
            }
            catch (RetryLimitExceededException /*dex */)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                //return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
            return RedirectToAction("Index");
        }

        public ActionResult ReviewStats(Player player)
        {
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebResurection/Views/Player/Create.cshtml
@model WebResurection.Domain.Model.Characters.Player

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Player</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Character.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Character.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Character.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Character.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Character.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Character.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="difficulty" value="Easy" class="btn btn-default" />
            </div>
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="difficulty" value="Medium" class="btn btn-default" />
            </div>
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" name="difficulty" value="Hard" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebResurection/Views/Player/Delete.cshtml
@model WebResurection.Domain.Model.Characters.Character

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<p class="has-error">@ViewBag.ErrorMessage</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HealthPoints)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HealthPoints)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Damage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Damage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebResurection/Views/Player/Details.cshtml
@model WebResurection.Domain.Model.Characters.Character

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Player</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HealthPoints)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HealthPoints)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Damage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Damage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImplementedStats)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Skill</th>
                    <th>Description</th>
                </tr>
                @foreach (var stat in Model.ImplementedStats)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => stat.Stat.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => stat.Stat.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => stat.Value)
                        </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebResurection/Views/Player/Edit.cshtml
@model WebResurection.Domain.Model.Characters.Player

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Player</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HealthPoints, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HealthPoints, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HealthPoints, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Damage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Damage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Damage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebResurection/Views/Player/Index.cshtml
@*Before Paging was created this was used
    @model IEnumerable<WebResurection.Domain.Model.Player>*@
@model PagedList.IPagedList<WebResurection.Domain.Model.Characters.Character>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css"/>


@{
    ViewBag.Title = "Players";
}

<h2>Players</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Player", FormMethod.Get))
{
    <p>
        Find by Name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search"/>
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
            
        </th>
        <th>
            Health Points
        </th>
        <th>
            Damage
        </th>
        <th>
            @Html.ActionLink("Joined On", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HealthPoints)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Damage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreateDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>
<br />
Page @((Model.PageCount < Model.PageNumber)? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))